### ISSUE TITLE
Plan to make time picker

### ISSUE THREAD

**Issue by rizkiandrianto** [andreystarkov/react-mobile-scrolldatetimepicker#1]
Would you plan to make time picker only?

**Comment by andreystarkov** [comment]
Sure. Its pretty easy,  (just add an param/checks to lib/DatePicker.js). But i'll do that bit later.

As a temporary solution should work:

`
  dateFormat={['YYYY', 'MM', 'DD', 'hh', 'mm']},
`

And hide first three cols via css

`
   .datepicker-col-1:nth-child(-n+3) { display: none; }
`

(Not tested, actually, but you can try.)

**Comment by rizkiandrianto** [comment]
Thanks, Great hacks :joy:
